# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
