# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='location',
        ),
        migrations.RemoveField(
            model_name='sourcefeed',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
