# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0002_auto_20160214_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('source_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='curator.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
