# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 04:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curator', '0003_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceFeed',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='curator.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='feed',
            name='source_name',
        ),
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
