# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0003_auto_20160321_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawarticle',
            old_name='source',
            new_name='source_feed',
        ),
    ]
