# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0004_auto_20160216_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curator.Source'),
        ),
    ]
