# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0005_auto_20160321_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcefeed',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
