# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0006_auto_20160321_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawarticle',
            name='source_feed',
        ),
        migrations.AddField(
            model_name='rawarticle',
            name='source_feed',
            field=models.ManyToManyField(to='curator.SourceFeed'),
        ),
    ]
