# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0007_curatorinvites'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatorinvites',
            name='invite_sent',
            field=models.BooleanField(default=False),
        ),
    ]
