# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 22:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0008_auto_20160321_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawarticle',
            name='date_crawled',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 26, 22, 5, 52, 344655, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
