# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0009_rawarticle_date_crawled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleclassification',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='curator.RawArticle'),
        ),
    ]
