# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 04:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0012_remove_sourcefeed_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcefeed',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
