# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 04:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0013_auto_20160328_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleclassification',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articleclassification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rawarticle',
            name='source_feed',
        ),
        migrations.DeleteModel(
            name='ArticleClassification',
        ),
        migrations.DeleteModel(
            name='RawArticle',
        ),
    ]
