# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 04:25
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curator', '0014_auto_20160329_0424'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('sentiment', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=400)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
                ('date_crawled', models.DateTimeField(auto_now=True)),
                ('source_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_feed', to='curator.SourceFeed')),
            ],
        ),
        migrations.AddField(
            model_name='articleclassification',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='curator.RawArticle'),
        ),
        migrations.AddField(
            model_name='articleclassification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
