# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 03:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0015_auto_20160329_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleclassification',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curator.RawArticle'),
        ),
        migrations.AlterField(
            model_name='articleclassification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
