# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0016_auto_20160330_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='article',
            name='source',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='rawarticle',
            name='title',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
